annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: system-upgrade-controller
apiVersion: v1
appVersion: v0.8.0
description: General purpose controller to make system level updates to nodes
home: https://github.com/rancher/system-charts/blob/dev-v2.6/charts/rancher-k3s-upgrader
name: system-upgrade-controller
sources:
- https://github.com/rancher/system-charts/blob/dev-v2.6/charts/rancher-k3s-upgrader
version: 100.0.1+up0.3.1
